services:
  astro:
    build: ./astro
    container_name: recipe_app_c
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
  backend:
    build: ./backend
    container_name: recipe_backend_c
    ports:
      - '5000:5000'
    stdin_open: true
    tty: true